version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.0-node
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction --optimize-autoloader
      - run:
          name: run tests
          command: ./vendor/bin/phpunit
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-php
    # - deploy:
    #     requires:
    #       - test-php
